Refined Textfield Design
ericgmoon/cognito-app pull request #11
Opened 2021-12-06 03:13 UTC by s-hane

Default:

![image](https://user-images.githubusercontent.com/48108455/144781207-8e8d8639-551b-4c58-a529-b41c0b852c4f.png)

On Focus:
![image](https://user-images.githubusercontent.com/48108455/144781250-45010588-f154-48b8-9f06-a02c1b956375.png)

2021-12-06 04:13 UTC, ericgmoon requested changes

2021-12-06 04:13 UTC, ericgmoon commented on src/components/Button/index.styles.ts
> +    margin: 8px;
Should there really be a margin built in to the button? I feel like margin is something that should be added when USING the button.

2021-12-06 04:13 UTC, ericgmoon commented on src/components/Button/index.styles.ts
> +    margin: 8px;
Should there really be a margin built in to the button? I feel like margin is something that should be added when USING the button.

2021-12-06 04:13 UTC, ericgmoon commented on src/components/Login/index.stories.tsx
> +  title: 'Components/Login',
This is a page, so should be in the `Pages/` folder

2021-12-06 04:13 UTC, ericgmoon commented on src/components/Login/index.tsx
> +// interface LoginProps {
Unused code - remove

2021-12-06 04:13 UTC, ericgmoon commented on src/components/Login/index.tsx
> +      <TextField placeholder="Email" {...register('email', { required: true, pattern: /^\S+@\S+$/i })} />
I feel like we should move the contents of the register out, as more complex forms will result in the DOM tree getting less readable.

2021-12-07 09:03 UTC, s-hane commented
![image](https://user-images.githubusercontent.com/48108455/144998934-8d4d6150-14e6-44f8-bb46-b782aff62d16.png)

2021-12-09 01:11 UTC, ericgmoon commented on src/components/Pages/LoginPage/index.stories.tsx
> +import LoginPage from '.';
Rename page to `SignInPage`?

2021-12-09 01:12 UTC, ericgmoon commented on src/components/Login/index.tsx
> +const Login = (/* { mobile = false }: LoginProps */) => {
Rename to `SignIn`?

2021-12-09 01:13 UTC, ericgmoon commented on src/components/Pages/LoginPage/index.stories.tsx
> +Default.args = {
I don't see any use of this prop, `placeholder` in the component. Is it meant to be here?

2021-12-09 01:13 UTC, ericgmoon commented on src/components/Login/index.styles.ts
> +        margin: 12px;
Incorrect margin here?

2021-12-09 01:14 UTC, ericgmoon commented on src/components/Login/index.tsx
> +    if (type === 'pattern') {
switch-case feels more appropriate here, as we'll be adding on more error messages over time

2021-12-09 01:14 UTC, ericgmoon commented on src/components/Login/index.tsx
> +    let error;
The `error` variable is unnecessary. We could just return within the body of each if statement.

2021-12-09 02:24 UTC, s-hane commented on src/theme.ts
> +      main: '#808080',
This is copied straight from our figma idk what you mean by dark child

2021-12-09 02:24 UTC, s-hane commented on src/components/Login/index.tsx
> +const Login = (/* { mobile = false }: LoginProps */) => {
That’s been done

2021-12-09 02:24 UTC, s-hane commented on src/components/Login/index.styles.ts
> +        margin: 12px;
Why?

2021-12-09 02:24 UTC, s-hane commented on src/components/Login/index.tsx
> +    if (type === 'pattern') {
Okay

2021-12-09 02:25 UTC, s-hane commented on src/components/Login/index.tsx
> +    let error;
Yep I changed this already haven’t put it through yet

2021-12-09 02:25 UTC, s-hane commented on src/components/Login/index.tsx
> +  console.log(errors);
Ok

2021-12-09 02:25 UTC, s-hane commented on src/components/Pages/LoginPage/index.tsx
> +  const isMd = useMediaQuery(theme.breakpoints.up('md'));
Checks screen size and changes variables accordingly

2021-12-09 02:25 UTC, s-hane commented on src/components/Pages/LoginPage/index.tsx
> +  const getOrientation = () : ('vertical' | 'horizontal' | undefined) => {
No

2021-12-09 04:30 UTC, ericgmoon commented on src/components/Login/index.styles.ts
> +        margin: 12px;
As in, the line indent/file margin is wrong (compare to the indent above)

2021-12-09 04:30 UTC, ericgmoon commented on src/components/Pages/LoginPage/index.tsx
> +  const isMd = useMediaQuery(theme.breakpoints.up('md'));
Not sure if `isMd` is the most suitable name

2021-12-09 06:21 UTC, s-hane commented on src/components/Pages/LoginPage/index.tsx
> +  const isMd = useMediaQuery(theme.breakpoints.up('md'));
Its checking if screen size is Md <- which is an MUI specified name

2021-12-09 10:11 UTC, ericgmoon requested changes

2021-12-09 10:11 UTC, ericgmoon commented on src/auth/index.ts
> +export const SignIn = async (
Wrong case

2021-12-09 10:11 UTC, ericgmoon commented on src/stories/Header.tsx
> +export const Header = ({ user, onSignIn, onLogout, onCreateAccount }: HeaderProps) => (
Undo changes to stories folder

2021-12-10 04:04 UTC, ericgmoon approved these changes

2021-12-10 04:26 UTC, merged