WP-46 Follow `theme.ts` spacing for CSS styles, move `pages` to be a separate package
ericgmoon/cognito-app pull request #14
Opened 2021-12-10 09:28 UTC by ericgmoon

Followed documentation on https://mui.com/customization/spacing/

2021-12-10 10:06 UTC, s-hane requested changes

2021-12-10 10:06 UTC, s-hane commented on src/App.tsx
> +      >Confirm
Test code still here

2021-12-10 10:06 UTC, s-hane commented on src/components/TextField/index.styles.ts
> +    width: ${({ theme }) => theme.spacing(45)};
shouldn't use spacing for widths

2021-12-10 10:07 UTC, ericgmoon commented on src/App.tsx
> +      >Confirm
Oops I wasn't meant to commit this file. Thank you for catching this

2021-12-11 00:33 UTC, s-hane requested changes

2021-12-11 00:33 UTC, s-hane commented on src/components/Button/index.styles.ts
> +    padding-bottom: ${({ theme }) => theme.spacing(2)};
You deleted border radius?

2021-12-11 00:33 UTC, s-hane commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
These aren't the same value, have you checked what it looks like with this margin, I remember changing from 16 -> 12 because the spacing looked too large

2021-12-11 00:34 UTC, ericgmoon commented on src/components/Button/index.styles.ts
> +    padding-bottom: ${({ theme }) => theme.spacing(2)};
Yeah, because I decided to use `theme.shape.borderRadius`, which is already used by the internal MUI styles. I have tested this using inspect element on storybook

2021-12-11 00:34 UTC, ericgmoon commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
I'm aware they're not the same, but making the increments `4px` would defeat the purpose of standardising the increments, as the increment is too small; imo.

2021-12-11 00:35 UTC, ericgmoon commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
I think we should just aim for all spacing to be increments of `8px`. Thoughts?

2021-12-11 00:36 UTC, ericgmoon commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
An alternative is to add set steps for spacing. eg. I could do:
```
spacing: [0, 2, 4, 8, 12, 16, 32, 64, 128]
```
Then call these as:
```
theme.spacing(4); // 12px
theme.spacing(1); // 2px
```
Would this be better? The problem with this solution is that if we want to add smaller increment steps in the future, we would have to refactor significantly.

2021-12-11 00:50 UTC, s-hane commented on src/components/Button/index.styles.ts
> +    padding-bottom: ${({ theme }) => theme.spacing(2)};
Okay

2021-12-11 00:51 UTC, s-hane commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
Have you seen how it looks

2021-12-11 00:52 UTC, s-hane commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
If you are fine with it then happy with that

2021-12-11 00:55 UTC, s-hane approved these changes

2021-12-11 00:56 UTC, ericgmoon commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
Yeahh I have

2021-12-11 00:56 UTC, ericgmoon commented on src/components/SignIn/index.styles.ts
> +  margin: ${({ theme }) => theme.spacing(2)};
![image](https://user-images.githubusercontent.com/32473932/145657892-0cdf4683-5fca-44ba-857b-be7a2d30ac51.png)

2021-12-11 00:56 UTC, merged