WP-58 Add EventCell component
ericgmoon/cognito-app pull request #35
Opened 2021-12-26 07:50 UTC by ericgmoon

![image](https://user-images.githubusercontent.com/32473932/147402192-c9c6209f-05c0-400c-bd85-91e0d4926a67.png)
![image](https://user-images.githubusercontent.com/32473932/147402194-69b80856-62cc-49af-8c8b-5764d714fc18.png)

2021-12-26 09:21 UTC, ericgmoon commented
![image](https://user-images.githubusercontent.com/32473932/147404000-c8169308-ba68-4dcb-b2cf-5a70fd498488.png)
![image](https://user-images.githubusercontent.com/32473932/147404010-1bece83c-6e74-4a6f-8276-1dc486621724.png)

2021-12-27 01:01 UTC, ericgmoon commented
Switched to using MUI Card. Now there's a background shadow, which I think looks better anyways

![image](https://user-images.githubusercontent.com/32473932/147424466-f6c77b5d-26b1-4fae-b76c-bb8f52e16246.png)
![image](https://user-images.githubusercontent.com/32473932/147424472-5765be9d-b0ed-47c2-87d5-2c530b67cc1f.png)
![image](https://user-images.githubusercontent.com/32473932/147424478-8bf6fb8a-e2b4-4566-bc50-a1f15b75cfce.png)

2021-12-27 01:23 UTC, ericgmoon commented
Added a disabled option. On hover over the button, the `disabled` cursor is displayed.
![image](https://user-images.githubusercontent.com/32473932/147425195-391497d5-d82a-458c-afc1-bca409b1dbb5.png)

2021-12-28 06:44 UTC, ericgmoon commented
Added online circle:

![image](https://user-images.githubusercontent.com/32473932/147536597-7220451b-3a0c-4a6c-917a-7addc24d1ba5.png)

2021-12-28 08:23 UTC, s-hane requested changes

2021-12-28 08:23 UTC, s-hane commented on src/components/EventCell/index.styles.ts
> +const ActionButton = styled(ButtonBase)<ActionButtonProps>`
Why not use the button component we created, I just styled the 'outlined' variant of our own button component for consistency.

2021-12-28 09:11 UTC, s-hane commented
Also some of the fonts look like Roboto rather than Montserrat idk if that's just me

2021-12-29 01:26 UTC, ericgmoon commented on src/components/EventCell/index.styles.ts
> +const ActionButton = styled(ButtonBase)<ActionButtonProps>`
I wrote it custom because it looked worse color-wise, but sure - have replaced it with the Button component.

![image](https://user-images.githubusercontent.com/32473932/147618763-a853bd88-a8f3-40f6-9169-ea650ccd7dbd.png)
![image](https://user-images.githubusercontent.com/32473932/147618765-3b601757-285d-43ec-8428-9c375bda9f93.png)
![image](https://user-images.githubusercontent.com/32473932/147618771-ee9a1a03-2957-4a41-920d-f5dd535ecdb7.png)
![image](https://user-images.githubusercontent.com/32473932/147618775-ea625dc6-8a08-4aac-a550-6b20188a9bb0.png)

2021-12-29 01:33 UTC, ericgmoon commented
Can confirm it's `Montserrat`:
![image](https://user-images.githubusercontent.com/32473932/147619048-b68db945-8bc6-4b59-ab28-b43f7921bf19.png)

Current:
![image](https://user-images.githubusercontent.com/32473932/147619061-6694ae9b-c059-4048-a823-48a8149dcf4d.png)

Using Roboto:
![image](https://user-images.githubusercontent.com/32473932/147619053-a0d32168-8414-404f-b696-81dfdfd29509.png)

2021-12-29 03:09 UTC, s-hane commented
> Can confirm it's `Montserrat`: ![image](https://user-images.githubusercontent.com/32473932/147619048-b68db945-8bc6-4b59-ab28-b43f7921bf19.png)
> 
> Current: ![image](https://user-images.githubusercontent.com/32473932/147619061-6694ae9b-c059-4048-a823-48a8149dcf4d.png)
> 
> Using Roboto: ![image](https://user-images.githubusercontent.com/32473932/147619053-a0d32168-8414-404f-b696-81dfdfd29509.png)

No I meant on the button, you can tell the font is different, compare your old one and new one

2021-12-29 03:20 UTC, ericgmoon commented
Ahh right, yep you're right.

2021-12-29 03:40 UTC, s-hane approved these changes

2021-12-29 03:40 UTC, s-hane commented on src/components/EventCell/index.styles.ts
> +const ActionButton = styled(ButtonBase)<ActionButtonProps>`
have you pushed your changes? I can't see them

2021-12-29 03:40 UTC, s-hane commented on src/components/EventCell/index.styles.ts
> +    padding-bottom: ${({ theme }) => theme.spacing(1)};
cant you just do padding: `${({ theme }) => theme.spacing(1, 2)};`

2021-12-29 03:43 UTC, ericgmoon commented on src/components/EventCell/index.styles.ts
> +    padding-bottom: ${({ theme }) => theme.spacing(1)};
Good suggestion - will include in next PR

2021-12-29 03:43 UTC, merged