Link tutorial page backend
ericgmoon/cognito-app pull request #62
Opened 2022-04-06 08:40 UTC by s-hane

2022-04-06 09:14 UTC, ericgmoon commented on backend/src/api/v1/tutorials/endpoints/putBook.ts
> +const MSINDAY = 86400000;
MS_IN_DAY snake case for constants please

2022-04-06 09:14 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
>  const MSINWEEK = 604800000;
camel case please

2022-04-08 14:05 UTC, ericgmoon approved these changes

2022-08-05 01:52 UTC, ericgmoon requested changes

2022-08-05 01:52 UTC, ericgmoon commented on src/services/tutorials/utils.ts
> +  if (tutorial.attendees.some((student) => student.studentId === getCurrentUserId())) {
Would be good to write some tests for this util function

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +            <LoadingWrapper>
Use the `LoadingWrapper` component from `components/PageLayout`

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +            <LoadingWrapper>
For an example, see how I handle loading in `VideoPlayerPage`

2022-08-05 01:52 UTC, ericgmoon commented on src/components/WeekCalendar/types.ts
> +  onJoin?: () => {},
The issue with this approach is if `WeekCalendar` contains events of DIFFERENT types requiring different `onBook` functions, no?

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +        return 'chemistry';
you can delete this line

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +        return 'physics';
you can delete this line too,

```
case 'phys11':
case'phys12':
return 'physics'
```

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +  const toSentenceCase = (sentence: string) =>
util function?

2022-08-05 01:52 UTC, ericgmoon commented on src/pages/TutorialsPage/index.tsx
> +  const [args] = useState({
If this is a static value, why do we need to use `useState`?

2022-08-05 01:58 UTC, s-hane commented on src/services/tutorials/utils.ts
> +  if (tutorial.attendees.some((student) => student.studentId === getCurrentUserId())) {
fine

2022-08-06 07:28 UTC, ericgmoon approved these changes
Approving with suggestions. Make sure you resolve merge conflict as well.

2022-08-06 07:28 UTC, ericgmoon commented on src/services/tutorials/index.ts
> +      invalidatesTags: (arg: any) => [{ type: 'Tutorials', id: arg }],
Shouldn't the id here be `arg.id`?

2022-08-06 07:28 UTC, ericgmoon commented on src/services/tutorials/index.ts
> +        const { startDatetime, endDatetime, courses } = arg;
I don't think `courses` as a comma-separated parameter is very intuitive. Shouldn't it be passed around as an array, which then gets transformed into a comma-separated input here?

2022-08-06 10:43 UTC, ericgmoon approved these changes

2022-08-06 10:52 UTC, merged