WP-86 Write backend video fetching logic
ericgmoon/cognito-app pull request #67
Opened 2022-08-03 00:41 UTC by ericgmoon

Changes from this PR:
- Expose `description` field for videos from the backend
- Provide a mechanism for children pages to control the loading state (via `startLoading` and `finishLoading` --> this could be implemented as a custom hook further down the line)
- Write a working storybook and tests for the `VideoPlayerPage`
- Implement video player
- Write RTK query for fetching individual videos
- Minor bug fixes

There are a few improvements to the UI I want to make, but I'll raise that as a separate PR. This is what we have for the moment:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/32473932/182500024-3ade73b2-21bf-4b7c-95e7-f8d27c6c23c6.png">

The video player page also includes breadcrumbs for easy navigation:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/32473932/182500124-a51f4fe3-19cc-4f4a-8c49-dab27acfac35.png">

2022-08-03 04:04 UTC, s-hane requested changes

2022-08-03 04:04 UTC, s-hane commented on src/components/VideoPlayer/index.tsx
> +};
Shouldn't this be in utils so other components can use this

2022-08-03 04:04 UTC, s-hane commented on src/components/VideoPlayer/index.tsx
> +const SideBar = ({ resources = [], relatedVideos = [], currentVideoId } : SideBarProps) => (
why is this not another component?

2022-08-03 04:04 UTC, s-hane commented on src/pages/VideoPlayerPage/index.tsx
> +  if (isSuccess) finishLoading();
why don't you just use the isLoading state??

2022-08-03 12:31 UTC, ericgmoon commented on src/components/PageLayout/index.tsx
> -        <Content decorate={decorate} loading={loading}>{children}</Content>
It's because we have structured our pages like components. For example, the page should have a loading animation while the video details are being fetched in `VideoPlayerPage`.

Individual components can have its own loading, but I think loading should be a global state for page components.

It doesn't make sense to have two different states control page-wide loading - that would result in nightmarish debugging in the future

2022-08-03 12:31 UTC, ericgmoon commented on src/components/VideoPlayer/index.tsx
> +};
Fair, I'll make that change.

2022-08-03 12:32 UTC, ericgmoon commented on src/components/VideoPlayer/index.tsx
> +const SideBar = ({ resources = [], relatedVideos = [], currentVideoId } : SideBarProps) => (
Because it's only ever going to be used by the `VideoPlayer` and nothing else. It's not going to be a reused component, ever. I've separated it out as a separate function purely for code clarity purposes

2022-08-03 12:33 UTC, ericgmoon commented on src/pages/VideoPlayerPage/index.tsx
> +  if (isSuccess) finishLoading();
`isLoading` wasn't behaving as expected - even my current version seems to be broken in the same way though; let me investigate and update this PR.

2022-08-03 13:19 UTC, ericgmoon commented on src/pages/VideoPlayerPage/index.tsx
> +  if (isSuccess) finishLoading();
Fixed

2022-08-03 13:20 UTC, ericgmoon commented on src/components/PageLayout/index.tsx
> -        <Content decorate={decorate} loading={loading}>{children}</Content>
Nevermind, after further thinking you're right - individual components should handle their own loading, including pages. That's not how I intended for `PageLayout` to be used, but RTK Query kinda forces it to be done that way.

This way, we can implement things like skeletons instead of circular loading.

2022-08-04 01:19 UTC, s-hane approved these changes

2022-08-04 01:19 UTC, merged